### ISSUE TITLE
`oc plugin cleanup` fails for shallow clones (--depth=1)

### ISSUE THREAD

**Issue by bittner** [appuio/oc-plugins#7]
[Due to the use of](https://github.com/appuio/oc-plugins/blob/master/cleanup/cleanup.sh#L17) `HEAD~1` applying `oc plugin cleanup` on shallow clones, or simply repositories with just a single commit, fails.

The implementation should be more robust, and not fail.

**Comment by bittner** [comment]
The current implementation [will not collect any old images](https://github.com/appuio/oc-plugins/blob/master/cleanup/cleanup.sh#L78-L84) if the related commit hashes are not drawn from the Git history.

It probably makes sense to reverse the deletion logic, having _preserved_ only those images that can be found in the commit history. This way, shallow commits will cause _all old images_ to be purged.

Caution! _This may be unwanted or unexpected, but should be allow to enforce, maybe._

**Comment by mikl** [comment]
If possible, it might also make sense to always preserve the latest X images, for some value of X (5, 10, etc.).

**Comment by bittner** [comment]
This is the default behavior, via the `--keep` option:
- [default value = 10](https://github.com/appuio/oc-plugins/blob/master/cleanup/plugin.yaml#L18-L21), currently
- [implementation](https://github.com/appuio/oc-plugins/blob/master/cleanup/cleanup.sh#L10) (KEEP var in the script)

**Comment by bittner** [comment]
We're introducing [Seiso](https://github.com/appuio/seiso) as our new, multi-featured cleanup tool. It [will address this shortcoming](https://github.com/appuio/seiso#how-does-it-work) where feasible.

## Related

* PR #10 (deprecation)
* PR https://github.com/appuio/container-oc/pull/39 (add Seiso to [appuio/oc](https://hub.docker.com/r/appuio/oc/))
